import fs from 'node:fs/promises';
import {dict,languages} from '../src/i18n.ts';
const host=(process.env.PUBLIC_SITE_URL||'https://color-manager-blanket.vercel.app').replace(/\/$/,'');
const template=await fs.readFile('dist/index.html','utf8');
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const content={
ko:{steps:['그룹을 만들고 HEX·RGB·HSL로 색상을 입력하세요.','견본을 눌러 코드를 복사하거나 그룹별로 정리하세요.','JSON으로 백업하고 CSS 변수나 PNG 팔레트로 내보내세요.'],imageSteps:['JPG·PNG·WebP 사진을 선택하세요.','대표색 개수와 투명 배경의 합성 색을 고른 뒤 추출하세요.','색을 선택해 팔레트에 추가하거나 미리보기에서 직접 찍으세요.'],contrastSteps:['글자색과 배경색을 HEX로 입력하세요.','대비 검사를 눌러 AA·AAA 결과를 확인하세요.','미리보기를 확인하고 두 색을 팔레트에 저장하세요.'],questions:['무료로 사용할 수 있나요?','사진과 팔레트가 서버에 저장되나요?','기존 컬러 매니저의 JSON을 가져올 수 있나요?'],answers:['로그인 없이 무료로 사용할 수 있습니다.','사진과 개인 팔레트는 이 브라우저 안에서 처리됩니다. 다른 기기로 옮기려면 JSON으로 내보내세요.','기존 version 5.0 JSON을 가져올 수 있습니다. 적용 전에 그룹과 색상 개수를 확인하고 병합 또는 교체를 선택하세요.']},
en:{steps:['Create a group and enter colors as HEX, RGB or HSL.','Tap a swatch to copy its code and organize colors by project.','Keep a JSON backup, or export CSS variables and PNG palettes.'],imageSteps:['Choose a JPG, PNG or WebP image.','Choose the number of colors and a background for transparent pixels.','Extract a palette or tap the preview to sample an individual color.'],contrastSteps:['Enter your text and background colors.','Run the check to see the AA and AAA results.','Review the preview and add the pair to your palettes.'],questions:['Is Color Manager free?','Are images and palettes uploaded?','Can I import my old Color Manager JSON?'],answers:['Yes. Use the tools for free without creating an account.','Your images and personal palettes are processed in this browser. Export JSON to transfer them to another device.','Yes. Version 5.0 JSON is supported. Preview the groups and colors before choosing merge or replace.']},
ja:{steps:['グループを作成しHEX・RGB・HSLで色を入力。','色見本を押してコードをコピーし、用途ごとに整理。','JSONで保存し、CSS変数やPNGパレットを書き出し。'],imageSteps:['JPG・PNG・WebP画像を選択。','色数と透明部分の背景を選択。','抽出した色を保存、または画像を押して色を選択。'],contrastSteps:['文字色と背景色を入力。','検査してAA・AAAの結果を確認。','プレビューを確認し色をパレットに追加。'],questions:['無料ですか？','画像はアップロードされますか？','以前のJSONは使えますか？'],answers:['アカウントなしで無料で利用できます。','画像とパレットはブラウザ内で処理。別端末へはJSONで移せます。','version 5.0に対応。内容を確認して結合または置換できます。']},
'zh-CN':{steps:['新建分组，输入HEX、RGB或HSL颜色。','点击色块复制代码，按项目整理。','备份JSON，或导出CSS变量及PNG调色板。'],imageSteps:['选择JPG、PNG或WebP图片。','选择颜色数量和透明区域的背景色。','提取后保存颜色，或点击预览逐点取色。'],contrastSteps:['输入文字和背景颜色。','运行检查，查看AA和AAA结果。','查看预览，并将颜色加入调色板。'],questions:['可以免费使用吗？','图片会被上传吗？','支持旧版JSON吗？'],answers:['无需账号即可免费使用。','图片和调色板在浏览器内处理。可用JSON转移到其他设备。','支持version 5.0。预览后可合并或替换。']},
'zh-TW':{steps:['新增群組，輸入HEX、RGB或HSL顏色。','點擊色塊複製代碼，按專案整理。','備份JSON，或匯出CSS變數及PNG調色盤。'],imageSteps:['選擇JPG、PNG或WebP圖片。','選擇顏色數量與透明區域的背景色。','擷取後儲存顏色，或點擊預覽逐點取色。'],contrastSteps:['輸入文字與背景顏色。','執行檢查，查看AA和AAA結果。','查看預覽，並將顏色加入調色盤。'],questions:['可以免費使用嗎？','圖片會被上傳嗎？','支援舊版JSON嗎？'],answers:['無需帳號即可免費使用。','圖片與調色盤在瀏覽器內處理。可用JSON轉移至其他裝置。','支援version 5.0。預覽後可合併或取代。']},
fr:{steps:['Créez un groupe et saisissez des couleurs HEX, RGB ou HSL.','Touchez une couleur pour copier son code et classez vos projets.','Sauvegardez en JSON, ou exportez en CSS et PNG.'],imageSteps:['Choisissez une image JPG, PNG ou WebP.','Choisissez le nombre de couleurs et le fond des pixels transparents.','Extrayez la palette ou touchez l’aperçu pour choisir une couleur.'],contrastSteps:['Saisissez la couleur du texte et du fond.','Vérifiez les résultats AA et AAA.','Examinez l’aperçu puis ajoutez les couleurs à vos palettes.'],questions:['Est-ce gratuit ?','Les images sont-elles envoyées ?','Puis-je importer mon ancien JSON ?'],answers:['Oui, sans créer de compte.','Les images et palettes restent dans le navigateur. Utilisez JSON pour les transférer.','Oui, la version 5.0 est prise en charge. Prévisualisez avant de fusionner ou remplacer.']},
de:{steps:['Gruppe erstellen und HEX-, RGB- oder HSL-Farben eingeben.','Farbe antippen, Code kopieren und nach Projekten ordnen.','JSON sichern oder CSS-Variablen und PNG-Paletten exportieren.'],imageSteps:['JPG-, PNG- oder WebP-Bild auswählen.','Farbanzahl und Hintergrund für transparente Pixel wählen.','Palette extrahieren oder eine Farbe in der Vorschau auswählen.'],contrastSteps:['Text- und Hintergrundfarbe eingeben.','AA- und AAA-Ergebnisse prüfen.','Vorschau ansehen und Farben zur Palette hinzufügen.'],questions:['Ist das kostenlos?','Werden Bilder hochgeladen?','Kann ich alte JSON-Dateien importieren?'],answers:['Ja, ohne Benutzerkonto.','Bilder und Paletten bleiben im Browser. Übertrage sie per JSON auf andere Geräte.','Ja, Version 5.0 wird unterstützt. Vor dem Zusammenführen oder Ersetzen wird eine Vorschau angezeigt.']},
es:{steps:['Crea un grupo y añade colores HEX, RGB o HSL.','Toca un color para copiar su código y organiza tus proyectos.','Guarda JSON o exporta variables CSS y paletas PNG.'],imageSteps:['Elige una imagen JPG, PNG o WebP.','Elige cuántos colores extraer y el fondo para la transparencia.','Extrae la paleta o toca la vista previa para elegir un color.'],contrastSteps:['Introduce los colores de texto y fondo.','Comprueba los resultados AA y AAA.','Revisa la vista previa y guarda los colores.'],questions:['¿Es gratuito?','¿Se suben las imágenes?','¿Puedo importar mi JSON anterior?'],answers:['Sí, sin crear una cuenta.','Las imágenes y paletas se procesan en el navegador. Usa JSON para transferirlas.','Sí, admite la versión 5.0. Revisa antes de combinar o reemplazar.']},
it:{steps:['Crea un gruppo e inserisci colori HEX, RGB o HSL.','Tocca un colore per copiare il codice e organizza i progetti.','Salva un JSON o esporta variabili CSS e palette PNG.'],imageSteps:['Scegli un’immagine JPG, PNG o WebP.','Scegli il numero di colori e lo sfondo per la trasparenza.','Estrai la palette o tocca l’anteprima per scegliere un colore.'],contrastSteps:['Inserisci i colori del testo e dello sfondo.','Verifica i risultati AA e AAA.','Controlla l’anteprima e aggiungi i colori alle palette.'],questions:['È gratuito?','Le immagini vengono caricate?','Posso importare il vecchio JSON?'],answers:['Sì, senza creare un account.','Immagini e palette restano nel browser. Usa JSON per trasferirle.','Sì, è supportata la versione 5.0. Controlla l’anteprima prima di unire o sostituire.']},
pt:{steps:['Crie um grupo e insira cores HEX, RGB ou HSL.','Toque numa cor para copiar o código e organize os projetos.','Guarde JSON ou exporte variáveis CSS e paletas PNG.'],imageSteps:['Escolha uma imagem JPG, PNG ou WebP.','Escolha a quantidade de cores e o fundo para transparência.','Extraia a paleta ou toque na prévia para escolher uma cor.'],contrastSteps:['Insira as cores do texto e do fundo.','Confira os resultados AA e AAA.','Veja a prévia e adicione as cores às paletas.'],questions:['É gratuito?','As imagens são enviadas?','Posso importar meu JSON antigo?'],answers:['Sim, sem criar conta.','Imagens e paletas ficam no navegador. Use JSON para transferi-las.','Sim, a versão 5.0 é compatível. Veja a prévia antes de mesclar ou substituir.']}
};
let urls=[];
for(const l of Object.keys(languages))for(const [key,path,stepsKey] of [['board','','steps'],['image','image-color-picker/','imageSteps'],['contrast','contrast-checker/','contrastSteps']]){const t=dict[l],c=content[l],url=`${host}/${l}/${path}`,title=`${t[key]} · ${key==='board'?'HEX / RGB / HSL':'Color Manager'}`,desc=key==='board'?t.intro+' '+c.steps.join(' '):key==='image'?t.imageHint+' '+t.pickHint:t.contrastHint;urls.push(url);const alternate=Object.keys(languages).map(k=>`<link rel="alternate" hreflang="${k}" href="${host}/${k}/${path}">`).join('')+`<link rel="alternate" hreflang="x-default" href="${host}/en/${path}">`;const json={"@context":"https://schema.org","@type":"WebApplication",name:'Color Manager — '+t[key],url,description:desc,applicationCategory:'DesignApplication',operatingSystem:'Any',inLanguage:l,offers:{'@type':'Offer',price:0,priceCurrency:'USD'}};const meta=`<title>${escape(title)}</title><meta name="description" content="${escape(desc)}"><link rel="canonical" href="${url}">${alternate}<meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="${url}"><meta property="og:image" content="${host}/og.png"><meta name="twitter:card" content="summary_large_image"><meta name="robots" content="${process.env.VERCEL_ENV==='preview'?'noindex,nofollow':'index,follow'}"><script type="application/ld+json">${JSON.stringify(json)}</script>`;
const seo=`<section class="seo-content"><h2>${escape(t[key])} · ${escape(t.help)}</h2><ol class="how-steps">${c[stepsKey].map(s=>`<li>${escape(s)}</li>`).join('')}</ol><h2>${escape(t.faq)}</h2>${c.questions.map((q,i)=>`<details><summary>${escape(q)}</summary><p>${escape(c.answers[i])}</p></details>`).join('')}<details><summary>${escape(t[key])}</summary><p>${escape(key==='image'?t.pickHint:key==='contrast'?t.contrastHint:t.privacyText)}</p></details><nav>${[['board',''],['image','image-color-picker/'],['contrast','contrast-checker/']].map(([k,p])=>`<a href="/${l}/${p}">${escape(t[k])}</a>`).join('')}<a href="https://imageto-pdf-eta.vercel.app/">Image to PDF</a></nav><nav aria-label="Languages">${Object.entries(languages).map(([k,n])=>`<a href="/${k}/${path}" lang="${k}">${n}</a>`).join('')}</nav></section>`;
let html=template.replace('lang="en"',`lang="${l}"`).replace('<title>Color Manager</title>',meta).replace('<div id="seo"></div>',`<div id="seo">${seo}</div>`);await fs.mkdir(`dist/${l}/${path}`,{recursive:true});await fs.writeFile(`dist/${l}/${path}index.html`,html)}
await fs.writeFile('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(url=>`<url><loc>${url}</loc></url>`).join('')+'</urlset>');await fs.writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${host}/sitemap.xml\n`);await fs.writeFile('dist/404.html','<!doctype html><html lang="en"><meta name="viewport" content="width=device-width"><title>Page not found · Color Manager</title><body style="font-family:system-ui;padding:10%;background:#eff4f6"><h1>404 · Page not found</h1><a href="/">Open Color Manager</a></body></html>');
console.log(`Generated ${urls.length} localized tool pages`);
