export type RGB={r:number,g:number,b:number};
export type Color={id:string,name:string,hex:string,favorite:boolean,version:number};
export type Group={id:string,title:string,note:string,colors:Color[],favorite:boolean,collapsed:boolean,version:number,x:number,y:number,width:number,height:number};
export type Workspace={schemaVersion:1,revision:number,groups:Group[],updatedAt:string};
export const uid=()=>crypto.randomUUID();
export const blank=():Workspace=>({schemaVersion:1,revision:0,groups:[],updatedAt:new Date().toISOString()});
export function hex(value:string){const s=value.trim().replace(/^#/,'');if(!/^([a-f0-9]{3}|[a-f0-9]{6})$/i.test(s))throw Error('invalid');return '#'+(s.length===3?[...s].map(x=>x+x).join(''):s).toUpperCase()}
export function rgb(s:string):RGB{const h=hex(s);return {r:parseInt(h.slice(1,3),16),g:parseInt(h.slice(3,5),16),b:parseInt(h.slice(5,7),16)}}
export function fromRGB(v:RGB){if(Object.values(v).some(x=>!Number.isInteger(x)||x<0||x>255))throw Error('invalid');return '#'+[v.r,v.g,v.b].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
export function hsl(s:string){let {r,g,b}=rgb(s);r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2;let h=0;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return [h,d?d/(1-Math.abs(2*l-1))*100:0,l*100]}
export function fromHSL(h:number,s:number,l:number){if(![h,s,l].every(Number.isFinite)||h<0||h>360||s<0||s>100||l<0||l>100)throw Error('invalid');h%=360;s/=100;l/=100;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;const a=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return fromRGB({r:Math.round((a[0]+m)*255),g:Math.round((a[1]+m)*255),b:Math.round((a[2]+m)*255)})}
export function format(s:string,f:string){if(f==='RGB'){const c=rgb(s);return `rgb(${c.r}, ${c.g}, ${c.b})`}if(f==='HSL'){const a=hsl(s).map(v=>Math.round(v*10)/10);return `hsl(${a[0]}, ${a[1]}%, ${a[2]}%)`}return hex(s)}
export function contrast(a:string,b:string){const lum=(s:string)=>{const c=rgb(s);const v=[c.r,c.g,c.b].map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});return v[0]*.2126+v[1]*.7152+v[2]*.0722};const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}
export const color=(h='#A8A0F5',name=''):Color=>({id:uid(),name,hex:hex(h),favorite:false,version:1});
export const group=(title:string,colors:Color[]=[],index=0):Group=>({id:uid(),title,note:'',colors,favorite:false,collapsed:false,version:1,x:24+(index%3)*360,y:24+Math.floor(index/3)*420,width:340,height:380});
export function validate(w:Workspace){if(w.groups.length>50||w.groups.reduce((a,g)=>a+g.colors.length,0)>1000||new Blob([JSON.stringify(w)]).size>5*1024**2)throw Error('limit');if(w.groups.some(g=>g.colors.length>100))throw Error('limit');return w}
const bounded=(v:unknown,def:number,min:number,max:number)=>typeof v==='number'&&Number.isFinite(v)?Math.min(max,Math.max(min,v)):def;
export function importData(raw:any):Workspace{if(!raw||!Array.isArray(raw.groups)||!(raw.schemaVersion===1||raw.version==='5.0'))throw Error('invalid');const w=blank();w.groups=raw.groups.map((g:any,i:number)=>{if(!g||typeof g.title!=='string'||g.title.length>80||typeof(g.note??'')!=='string'||(g.note??'').length>500)throw Error('invalid');let list=g.colors;if(!list&&Array.isArray(g.colorIds)&&Array.isArray(raw.colors))list=g.colorIds.map((id:string)=>raw.colors.find((c:any)=>c.id===id));if(!Array.isArray(list))throw Error('invalid');const n=group(g.title,list.map((c:any)=>{if(!c||typeof(c.name??'')!=='string'||(c.name??'').length>60)throw Error('invalid');return {...color(c.hex??fromRGB(c.rgb),c.name??''),favorite:!!c.favorite}}),i);const pos=g.canvas??g;return {...n,note:g.note??'',favorite:!!g.favorite,collapsed:!!g.collapsed,x:bounded(pos.x,n.x,0,10000),y:bounded(pos.y,n.y,0,10000),width:bounded(pos.width,340,280,1200),height:bounded(pos.height,380,200,1200)}});return validate(w)}
export function duplicate(g:Group){return {...structuredClone(g),id:uid(),version:1,colors:g.colors.map(c=>({...c,id:uid(),version:1})),x:g.x+24,y:g.y+24}}
export function cssExport(groups:Group[]){return ':root {\n'+groups.flatMap((g,i)=>g.colors.map((c,j)=>`  --group-${i+1}-color-${j+1}: ${c.hex};`)).join('\n')+'\n}\n'}
export const samples=[['#28374A','#657F8C','#AEC0BD','#E8DED1','#BC8068'],['#FFCF5C','#F88179','#8ECFC8','#A6A0F1','#F5EDD9'],['#182326','#5B7470','#AFC5B5','#ECE8DB','#BDA98B'],['#253A69','#5572BE','#8AB8D3','#E2EAF4','#EFAC67'],['#10161F','#263345','#A99DFF','#77C8B3','#F1F4FA'],['#663D40','#AD6662','#DF9C80','#F5D5AE','#FAECDD']];
